### ISSUE TITLE
EC2 배포

### ISSUE THREAD

**Issue by mmihye** [Link-MIND/Server#1]
## ✨ About Issue ✨
ec2 배포 하기

<br>

## ✅ Todo 
- [x] ec2 인스턴스 생성
- [x] rds 생성
- [x] 프로젝트 이름 변경
- [x] 테스트 api 추가
- [x] ec2 배포
