### ISSUE TITLE
[Feat] 카테고리 API 구현

### ISSUE THREAD

**Issue by mmihye** [Link-MIND/Server#15]
## ✨ About Issue ✨
카테고리 관련 API 개발

<br>

## ✅ Todo 

- [x] 카테고리 추가 
- [x] 세부 카테고리 조회
- [x] 카테고리 삭제
- [x] 카테고리 제목 편집
- [x] 전체 카테고리 조회
