### ISSUE TITLE
[Feat] Auth : 유저 설정 페이지, 마이페이지, fcm 동의 여부 수정 API

### ISSUE THREAD

**Issue by sss4920** [Link-MIND/Server#21]
## ✨ About Issue ✨

Auth : 유저 설정 페이지, 마이페이지, fcm 동의 여부 수정 API
<br>

## ✅ Todo 

- [x] 유저 설정 페이지 get 
- [x] 유저 마이 페이지 get
- [x] fcm 동의 여부 수정 api patch
