### ISSUE TITLE
[Feature] 카테고리 관련 테스트코드 작성하기

### ISSUE THREAD

**Issue by mmihye** [Link-MIND/Server#232]
## ✨ About Issue ✨
카테고리 관련 api 테스트코드 작성하기

<br>

## ✅ Todo 
- [ ] 전체 카테고리 조회
- [ ] 카테고리 우선순위 수정
- [ ] 카테고리 제목 수정
- [ ] 카테고리 삭제
- [ ] 카테고리 추가
- [ ] 세부 카테고리 조회
