### ISSUE TITLE
[Feature] 팝업 관련 api 구현

### ISSUE THREAD

**Issue by sss4920** [Link-MIND/Server#240]
## ✨ About Issue ✨
팝업 기능에 대해서 구현하겠습니다.
<br>

## ✅ Todo 

- [ ] queryDSL 테스트 결과 별 차이 없어서 production 문제 안생기게 주석처리
- [ ] 팝업 안보이기 기능
- [ ] 팝업 정보 보이기 기능
- [ ] 테스트
