### ISSUE TITLE
[Feature] 클립 및 타이머 에러처리

### ISSUE THREAD

**Issue by mmihye** [Link-MIND/Server#33]
## ✨ About Issue ✨
클립 및 타이머 에러처리

<br>

## ✅ Todo 
- [x] 클립 생성 50까지 -> 클립 생성은 50개 까지만 가능해요
- [x] 클립 이름 최대 10자
- [x] 타이머 최대 5개
- [x] 타이머 시간 형식 아니면 에러
