### ISSUE TITLE
[Fix] 타이머오류 고치기

### ISSUE THREAD

**Issue by mmihye** [Link-MIND/Server#71]
## ✨ About Issue ✨
타이머시간 포맷시 미국시간으로 포맷되는 오류 발생 -> 한국시간 지정해주기
<br>

## ✅ Todo 
- [x] 타이머 포맷시 한국시간 지정해주기
- [x] 타이머 생성시 이미 존재하는 카테고리면 예외처리
- [x] 완료된 타이머 시간비교시 월-일 차이 인식못함 해결
- [x] 완료된 타이머 요일 설정
